# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3529aa82637bf6d3d72f9932a2af67c1416fe9c5f73d041c046ed36365bcdedf570513eb2953e95cd7b9bbcd811b055e3b40f274be38c6235e89aae365d87d1

test:
  secret_key_base: b22cc4f7d377069a599c0a9f90effb557cabdb68610bccc1f5a0f0732f9dce440a53d9843dbd6a8685c28903a8ce8e60365d8953d75c5a865db1bf3300a4f9d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
